Torpedofix
Laci135IET/ivt-lab pull request #3
Opened 2020-04-17 20:13 UTC by Laci135

2020-04-17 20:25 UTC, Laci135IET commented on src/main/java/hu/bme/mit/spaceship/TorpedoStore.java
> +  private Random generator = new Random();
Add some comments here to clarify what the generator does.

2020-04-17 20:33 UTC, Laci135IET requested changes

2020-04-17 20:33 UTC, Laci135IET commented on src/main/java/hu/bme/mit/spaceship/TorpedoStore.java
> +  private Random generator = new Random();
Add some comments to clarify what the generator does.

2020-04-17 20:35 UTC, Laci135IET approved these changes

2020-04-17 20:36 UTC, merged

2020-05-10 14:44 UTC, Laci135 commented
A Laci135 fiók a helyi beállítások miatt laci98-ként jelenik meg (email cím alapján).